/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2021-01-19 16:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1611058306497L));
    _jspx_dependants.put("jar:file:/C:/projects/my%20projects/spring-projects/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-web/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/common/navbar.jsp", Long.valueOf(1611072803716L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1611070925184L));
    _jspx_dependants.put("jar:file:/C:/projects/my%20projects/spring-projects/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Bootstrap 4 Example</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark mb-3\">\r\n");
      out.write("\t<a href=\"/shop/index.jsp\" class=\"navbar-brand\">쇼핑몰</a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsible-navbar\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"collapsible-navbar\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/index.jsp\" class=\"nav-link\">홈</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("      \t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("        \t\t\t카테고리\r\n");
      out.write("\t\t      \t</a>\r\n");
      out.write("\t\t      \t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t      \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t      \t</div>\r\n");
      out.write("\t\t    </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"navbar-nav \">\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/loginform.jsp\" class=\"nav-link\">로그인</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/form.jsp\" class=\"nav-link\">회원가입</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/cart/list.jsp\" class=\"nav-link\">장바구니</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/order/list.jsp\" class=\"nav-link\">주문내역</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/my/info.jsp\" class=\"nav-link\">내정보</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a href=\"/shop/logout.jsp\" class=\"nav-link\">로그아웃</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav> ");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 새 상품 시작 -->\r\n");
      out.write("\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header font-weight-bold\">새 상품</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 새 상품 정보 리스트 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- 상품정보 반복 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 상품정보 반복 끝 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 새 상품정보 리스트 끝 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 새 상품 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 추천 상품 시작 -->\r\n");
      out.write("\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header font-weight-bold\">추천상품</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 추천 상품정보 리스트 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- 추천 상품정보 반복 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 추천 상품정보 반복 끝 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card \">\r\n");
      out.write("\t \t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t  \t\t\t\t\t\t\t<a href=\"/shop/product/detail.jsp\"><img class=\"img-thumbnail\" src=\"/shop/resources/images/book.jpg\" alt=\"Card image\"></a>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<strong>불안한 마음을 잠재우는 범</strong>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">하주원</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small class=\"text-secondary\">올댓북스</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small><strong class=\"text-danger\">16,200</strong> 원 (10% 할인)</small> \r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<small>900원 적립</small>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t<div class=\"mt-3\">\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 무료 배송 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-primary\">무료배송</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 등록일 기준 7일 이내 상품인 경우 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-success\">새 상품</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<!-- 상품 테이블의 베스트셀러 여부가 Y일 때 표시 -->\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t\t<span class=\"badge badge-info\">베스트셀러</span>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 추천 상품 정보 리스트 끝 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-12 mt-5\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row mt-3 mb-5\"  style=\"margin: 0;\">\r\n");
      out.write("\t<div class=\"col-12 bg-dark text-white py-3\">\r\n");
      out.write("\t\t<div>개인정보보호 사항을 준수합니다.</div>\r\n");
      out.write("\t\t<div>기타 문의사항은 아래의 전화번호로 전화바랍니다.</div>\r\n");
      out.write("\t\t<div>전화번호 : 010-1234-5678</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/common/navbar.jsp(18,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /WEB-INF/views/common/navbar.jsp(18,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/navbar.jsp(18,9) '${categories }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t        \t<a class=\"dropdown-item\" href=\"list.do?catno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.typeNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t      \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
